name: flutter-action
on: push
jobs:
  test:
    name: actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter doctor --android-licenses
    - run: sudo apt install ninja libgtk-3-dev android-studio -y
    - run: flutter pub get
    - run: flutter --version
    - run: flutter doctor -v
    - run: flutter run -d all
